# Informação da aplicação
info:
  component: 'Rent a Tent API'
  build:
    version: '@project.version@'
    name: '@project.name@'
spring:
  profiles: default
  application:
    name: rentonator
  datasource:
    rentonator:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://betroom.chzhvascxjqk.sa-east-1.rds.amazonaws.com:3306/rentonator
      username: app_betroom
      password: Sfpug6ym
      testWhileIdle: true
      validationQuery: SELECT 1
server:
  context-path: /rentonator
logging:
  config: classpath:log4j2-dev.xml